# Generated by Django 6.0.4 on 2026-04-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Stand',
        ),
    ]
