# Generated by Django 6.0.4 on 2026-04-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
