# Generated by Django 6.0.4 on 2026-04-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_rename_date_payment_due_date_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='date',
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.payment'),
        ),
        migrations.AddField(
            model_name='alert',
            name='sent_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='sent_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.client'),
        ),
    ]
