# Generated by Django 6.0.4 on 2026-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_remove_alert_date_alert_created_at_alert_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Property App', max_length=100)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
        ),
    ]
