# Generated by Django 6.0.4 on 2026-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0005_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Property System', max_length=255),
        ),
    ]
