# Generated by Django 6.0.4 on 2026-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0006_alter_sitesettings_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='stand',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stand',
            name='size_sqm',
            field=models.DecimalField(decimal_places=2, default='000', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stand',
            name='stand',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stand',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stand',
            name='image',
            field=models.ImageField(upload_to='stands/'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
