# Generated by Django 6.0.4 on 2026-06-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0008_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stands.allocation'),
        ),
    ]
