# Generated by Django 6.0.4 on 2026-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0010_sitesettings_address_sitesettings_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Zwide Property Development Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='stand',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
